[build]
default-target = "aarch64-unknown-linux-gnu"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get --assume-yes install alsa:$CROSS_DEB_ARCH alsa-utils:$CROSS_DEB_ARCH",
    "apt-get --assume-yes install libasound2-dev:$CROSS_DEB_ARCH"
]