name: CD

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION_STABLE: 1.83.0
  RUST_VERSION_NIGHTLY: nightly-2024-11-26
  CRATE_PATHS: .

jobs:

  check-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.retrieve-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check CHANGELOG.md file exists
        run: '[ -f CHANGELOG.md ]'
      - name: Check unreleased version is defined in CHANGELOG.md
        run: grep '^\#\# \[Unreleased\] - yyyy-mm-dd$' CHANGELOG.md
      - name: Check and retrieve version
        id: retrieve-version
        run: bash .github/workflows/scripts/get_version.sh

  test-ubuntu:
    runs-on: ubuntu-24.04
    needs: check-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test
  
  build-x86_64:
    runs-on: ubuntu-24.04
    needs: test-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: bash .github/workflows/scripts/build_release.sh x86_64 ${{github.event.repository.name}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.repository.name}}_x86_64.tar.gz
          path: ${{github.event.repository.name}}_x86_64.tar.gz
  
  build-aarch64:
    runs-on: ubuntu-24.04
    needs: test-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: bash .github/workflows/scripts/build_release.sh aarch64 ${{github.event.repository.name}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.repository.name}}_aarch64.tar.gz
          path: ${{github.event.repository.name}}_aarch64.tar.gz

  create-release:
    permissions: write-all
    runs-on: ubuntu-24.04
    needs:
      - check-version
      - build-x86_64
      - build-aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Apply version and date in CHANGELOG.md file
        run: sed -i "s/^\#\# \[Unreleased\] - yyyy-mm-dd$/\#\# [${{needs.check-version.outputs.version}}] - $(date +'%Y-%m-%d')/g" CHANGELOG.md
      - name: Push changes and create tag
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Release v${{needs.check-version.outputs.version}}
          tag: -a v${{needs.check-version.outputs.version}} -m 'Release v${{needs.check-version.outputs.version}}'
      - name: Add section for next version in CHANGELOG.md
        run: sed -i '/\#\# \[${{needs.check-version.outputs.version}}\]/i \#\# [Unreleased] - yyyy-mm-dd\n' CHANGELOG.md
      - name: Increment version in Cargo.toml
        run: bash .github/workflows/scripts/increment_version.sh ${{needs.check-version.outputs.version}}
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Prepare next release
      - name: Extract changelog
        run: sed -n '/\#\# \[${{needs.check-version.outputs.version}}/,/\#\# \[/p' CHANGELOG.md | sed '/\#\# \[/d' | sed '1{/^$/d}' | sed '1{/^$/d}' | sed '${/^$/d}' | sed '${/^$/d}' > version_changelog.md
      - uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{needs.check-version.outputs.version}}
          tag_name: v${{needs.check-version.outputs.version}}
          body_path: version_changelog.md
          files: |
            ${{github.event.repository.name}}_x86_64.tar.gz
            ${{github.event.repository.name}}_aarch64.tar.gz
